[package]
name = "duo-m3u"
version = "0.1.0"
authors = ["modeverv <modeverv@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glob = "0.3.0"
my-lib = {path = "../my-lib"}